import type { Metadata } from 'next'
import { Plus_Jakarta_Sans } from 'next/font/google'
import { PropsWithChildren } from 'react'
import './global.css'

const body = Plus_Jakarta_Sans({ subsets: ['latin'], variable: '--font-body' })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout(props: PropsWithChildren) {
  return (
    <html lang="en">
      <body className={body.variable}>{props.children}</body>
    </html>
  )
}