import "~/styles/globals.css";
import { Inter } from "next/font/google";
import { Toaster } from "react-hot-toast";
import AuthStatus from "~/components/auth-status";
import { Suspense } from "react";
import { Providers } from '~/components/second-prisma/providers'
import './globals.css'

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.variable}>
        <Providers>
          <Toaster />
          <Suspense fallback="Loading...">
            <AuthStatus />
          </Suspense>
          {children}
        </Providers>
      </body>
    </html>
  );
}